
import Navbar from '@/Component/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'
import GlobalState from '@/contaxt'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Best Shop',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GlobalState>
          <Navbar></Navbar>
          <div className='flex text-black  min-h-screen flex-col mt-[80px]'>
            {children}
          </div>
        </GlobalState>

      </body>
    </html>
  )
}
